org.example\:socketP\:1.0-SNAPSHOT=file:/home/kairav/dev/java/randomTry/socketP/
org.example\:threading\:1.0-SNAPSHOT=file:/home/kairav/dev/java/randomTry/threading/
org.kairav.Main\:my-javafx-app\:1.0-SNAPSHOT=file:/home/kairav/dev/java/fx_try/
