"""Comment model — reader discussion under a published post."""
from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING

from sqlalchemy import BigInteger, Boolean, Enum, ForeignKey, Index, Text, Uuid, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

# Type-only import: used so type checkers/linters know what `Post` and `User`
# are. The actual resolution happens at runtime via SQLAlchemy's registry.
if TYPE_CHECKING:
    from app.models.comment_report import CommentReport
    from app.models.post import Post
    from app.models.user import User


class CommentStatus(enum.StrEnum):
    """Lifecycle of a comment, mirroring design.md §9.2.

    - VISIBLE   — public, shown under the post
    - REPORTED  — a reader flagged it; hidden from everyone except admins
    - HIDDEN    — admin moderation removed it from public view
    """

    VISIBLE = "VISIBLE"
    REPORTED = "REPORTED"
    HIDDEN = "HIDDEN"


class Comment(TimestampMixin, Base):
    """A single comment someone left on a post.

    Comments are flat for now (no nested replies) — keeping the first version
    simple. `parent_id` is intentionally omitted; if threaded replies are ever
    needed, a self-referencing FK can be added with a small migration.

    `public_id` is the identifier exposed in URLs/API responses so commenters
    never leak their sequential internal `id`.
    """

    __tablename__ = "comments"

    # "list a post's comments, newest first" is the hot read query.
    __table_args__ = (Index("ix_comments_post_id_created_at", "post_id", "created_at"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    # Generated by Postgres (gen_random_uuid) so it cannot be guessed.
    public_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), server_default=text("gen_random_uuid()"), unique=True, index=True
    )
    post_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("posts.id", ondelete="CASCADE"), index=True
    )
    author_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    # Comment bodies are plain Markdown, rendered with the same safe renderer
    # as post bodies (never raw HTML), so they cannot be an XSS vector.
    content: Mapped[str] = mapped_column(Text)
    # Moderation state (see `CommentStatus`). Public lists only ever show
    # VISIBLE comments; admins can see and act on the rest.
    status: Mapped[CommentStatus] = mapped_column(
        Enum(CommentStatus, name="commentstatus", native_enum=False),
        default=CommentStatus.VISIBLE,
        server_default="VISIBLE",
        index=True,
    )
    # How many distinct readers have flagged this comment.
    # When >= COMMENT_REPORT_THRESHOLD, the comment is auto-hidden.
    report_count: Mapped[int] = mapped_column(
        BigInteger, server_default="0", nullable=False, index=True
    )

    post: Mapped["Post"] = relationship("Post", back_populates="comments")  # noqa: UP037
    author: Mapped["User"] = relationship("User", back_populates="comments")  # noqa: UP037
    reports: Mapped[list["CommentReport"]] = relationship(
        "CommentReport", back_populates="comment", cascade="all, delete-orphan"
    )  # noqa: UP037
