source = ~/.config/hypr/wallpaper.conf

wallpaper {
    monitor = eDP-1
    path = $wallpaper
    fit_mode = cover
}

wallpaper {
    monitor =
    path = $wallpaper
    fit_mode = cover
}

splash = false
ipc = true
