context.properties = {
    # Use high-quality Speex or Sox resampling algorithms
    resample.quality = 10
}

stream.properties = {
    # Set default sample rates (fallback and allowed rates)
    default.clock.rate          = 48000
    default.clock.allowed-rates = [ 44100 48000 88200 96000 192000 ]
    default.clock.min-quantum   = 32
    default.clock.max-quantum   = 8192
}
